cwm/cwm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from cwmapp.views import top, Login, register, setting, result, index, music, user, search, artist, album, create, delete, edit, Logout, star, good ,view_reply, create_reply, changepassword, upload, good_comment, premium_descreption, tos, register_premium, musdelete

app_name = 'cwm'

urlpatterns = [
    path('admin/', admin.site.urls),
    path( "", top ,name="top"),
    path( "login/", Login, name="Login"),
    path( "logout/", Logout, name="Logout" ),
    path( "register/", register ,name="register"),
    path( "setting/", setting ,name="setting"),
    path( "result/", result, name="result" ),
    path( "index/", index, name="index"),
    path( "create/<slug:idn>", create, name="create" ),
    path( "delete/<slug:idn>/<int:cid>", delete, name="delete" ),
    path( "edit/<slug:idn>/<int:cid>", edit, name="edit" ),
    path( "musdelete/<slug:idn>", musdelete, name="musdelete" ),
    path( "star/<slug:idn>", star, name="star" ),
    path( "good/<slug:idn>", good, name="good" ),
    path( "good_comment/<slug:idn>", good_comment, name="good_comment" ),
    path( "view_reply/<slug:idn>", view_reply, name="view_reply" ),
    path( "create_reply/<slug:idn>/<int:cid>", create_reply, name="create_reply" ),
    path( "music/<slug:idn>", music, name="mus" ),
    path( "user/<slug:idn>", user, name="user" ),
    path( "search/", search, name="search" ),
    path( "artist/<slug:id>", artist, name="artist" ),
    path( "album/<slug:id>", album, name="album" ),
    path( "changepassword/", changepassword, name="changepassword" ),
    path( "upload/", upload, name="upload" ),
    path( "premium_descreption", premium_descreption, name="premium_descreption" ),
    path( "tos", tos, name="tos" ),
    path( "register_premium", register_premium, name="register_premium" )
]

#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cwm/cwmapp/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import PermissionsMixin, BaseUserManager

from lib.utils import Utils
import datetime
import uuid
import random,string

'''class User( models.Model ):
    user_name = models.CharField( max_length = 50 )
    user_mail = models.EmailField( primary_key = True )
    user_pass = models.CharField( max_length = 30 )
    user_image = models.ImageField( upload_to = 'images/' )
    user_birthday = models.DateField()

    def __str__( self ):
        return self.user_mail'''

class UploadImage( models.Model ):#画像テーブル
    image = models.ImageField( upload_to = 'images/' )#一時的なイメージの建て替え

'''class Music( models.Model ):
    music_id = models.TextField( primary_key = True )
    music_star = models.IntegerField()#いらない
    music_ad = models.BooleanField()

    def __str__( self ):
        return self.music_id'''

class Comment( models.Model ):#コメントテーブル
    comment_id = models.AutoField( primary_key = True )#コメントのID
    #comment_user_mail = models.EmailField()#コメント下ユーザのメールアドレス
    comment_userid = models.CharField( max_length=100 )
    comment_music_id = models.TextField()#コメントされた音楽のID
    comment_text = models.TextField()#コメント本文
    comment_posted = models.DateTimeField( auto_now_add = True )#コメントした日時

    def __str__( self ):
        return str( self.comment_id )

""" class Result( models.Model ):
    result_comment_id = models.IntegerField()
    result_user_mail = models.EmailField()
    result_text = models.TextField()
    result_posted = models.DateTimeField( auto_now_add = True )

    def __str__( self ):
        return self.result_text """

class Reply( models.Model ):#返信テーブル
    reply_id = models.AutoField( primary_key = True )#返信のID
    reply_comment_id = models.IntegerField()#返信したコメントのID
    #reply_user_mail = models.EmailField()#返信したユーザのメールアドレス
    reply_userid = models.CharField( max_length=100 )
    reply_text = models.TextField()#返信本文
    reply_posted = models.DateTimeField( auto_now_add = True )#返信した日時

    def __str__( self ):
        return self.reply_userid

class LikeList( models.Model ):#いいねしたリストテーブル
    #like_user_mail = models.EmailField()#いいねしたユーザのメールアドレス
    like_userid = models.CharField( max_length=100 )
    like_music_id = models.TextField()#いいねした音楽のID

    def __str__( self ):
        return self.like_userid

class HistoryList( models.Model ):#履歴テーブル
    #history_user_mail = models.EmailField()#履歴のメールアドレス
    history_userid = models.CharField( max_length=100 )
    history_music_id = models.TextField()#履歴の音楽ID

    def __str__( self ):
        return self.history_userid

class Star( models.Model ):#評価テーブル
    #star_user_mail = models.EmailField()#評価したユーザのメールアドレス
    star_userid = models.CharField( max_length=100 )
    star_music_id = models.TextField()#評価した音楽のID
    star_num = models.IntegerField()#音楽に対する評価
    class Meta:#複合キー指定
        constraints = [
            models.UniqueConstraint( fields=[ 'star_userid', 'star_music_id' ], name='unique_star' )
        ]

class Good( models.Model ):#いいねテーブル
    #good_user_mail = models.EmailField()#いいねしたユーザのメールアドレス
    good_userid = models.CharField( max_length=100 )
    good_music_id = models.TextField()#いいねした音楽のID
    good_bool = models.BooleanField(default=False)#音楽に対するいいね
    class Meta:#複合キー指定
        constraints = [
            models.UniqueConstraint( fields=[ 'good_userid', 'good_music_id' ], name='unique_good' )
        ]

class GoodComment( models.Model ):
    gc_userid = models.CharField( max_length=25 )
    gc_comment_id = models.TextField()#いいねしたコメントのID
    gc_bool = models.BooleanField( default = False )#コメントに対するいいね
    class Meta:
        constraints = [
            models.UniqueConstraint( fields=[ 'gc_userid', 'gc_comment_id' ], name='unique_gc' )
        ]

class GoodCommentReply( models.Model ):
    gcr_userid = models.CharField( max_length = 25 )
    gcr_reply_id = models.TextField()
    gcr_bool = models.BooleanField( default = False )
    class Meta:
        constraints = [
            models.UniqueConstraint( fields=[ 'gcr_userid', 'gcr_reply_id' ], name='unique_gcr' )
        ]

class Music( models.Model ):#ユーザが投稿した音楽テーブル
    def save_full_track( instance, filename ):#フルの楽曲を保存するパス
        ext = filename.split('.')[-1]
        return f'{ Album.objects.get( album_id = instance.music_album_id ).album_userid }/albums/{ instance.music_album_id }/tracks/full/{ instance.music_id }.{ ext }'
    def save_preview_track( instance, filename ):#プレビューの楽曲を保存するパス
        ext = filename.split('.')[-1]
        return f'{ Album.objects.get( album_id = instance.music_album_id ).album_userid }/albums/{ instance.music_album_id }/tracks/pre/{ instance.music_id }.{ ext }'
    music_id = models.TextField(default=Utils.randomid, primary_key = True )#曲のID
    music_album_id = models.TextField()#所属するアルバムのID
    music_name = models.CharField( max_length = 100 )
    music_track_full = models.FileField( upload_to = save_full_track )#フルの音楽
    music_track_preview = models.FileField( upload_to = save_preview_track )#プレビュー音楽
    #music_userid = models.TextField()#投稿者のID
    
class Album( models.Model ):#ユーザが投稿したアルバムテーブル
    def save_album_image( instance, filename ):
        ext = filename.split( '.' )[ -1 ]
        return f'{ instance.album_userid }/albums/{ instance.album_id }/image/{ instance.album_id }.{ ext }'
    album_id = models.TextField(default=Utils.randomid, primary_key = True )#アルバムのID
    album_userid = models.TextField()#投稿者のID
    album_name = models.CharField( max_length = 100 )
    album_image = models.FileField( upload_to = save_album_image )

class UserManager( BaseUserManager ):
    use_in_migrations = True
  
    def _create_user(self, email, password, **extra_fields):#userid, 
        """Create and save a user with the given username, email, and
        password."""
        #if not userid:
        #    raise ValueError('The given email must be set')
        if not email:
            raise ValueError( 'The given email must be set' )
        email = self.normalize_email(email)
  
        user = self.model(email=email, **extra_fields)#userid=userid, 
        user.set_password(password)
        user.save(using=self._db)
        return user
  
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        #extra_fields.setdefault( 'last_login', datetime.datetime.now( pytz.timezone('Asia/Tokyo') ) )
        return self._create_user(email, password, **extra_fields)
  
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
  
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
  
        return self._create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """

    def save_user( instance, filename ):
        return f'{ instance.userid }/image/{ filename }'#ユーザ画像
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=50,
        help_text=_(
            "この名前は公開されます。"
        ),
        validators=[username_validator],
        error_messages={
            "msg": _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_("email address"), blank=True, primary_key=True)
    userid = models.CharField(
        _( "userid" ),
        max_length=100,
        unique=True,
        default=Utils.randomid,
        help_text=_(
            "この名前は公開されません。"
        ),
        validators = [username_validator],
        error_messages={
            "msg": _( "fuck!" )
        }
    )
    image = models.ImageField( upload_to = save_user )
    is_premium = models.BooleanField(
        default=False
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        #abstract = True

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_short_name(self):
        """Return the short name for the user."""
        return self.username

    def mail_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)
    #def __str__( self ):
    #    return self.username

cwm/cwmapp/forms.py
from django import forms
from .models import Comment, UploadImage, CustomUser, Reply,Music,Album

class Register(forms.Form):
    user_name = forms.CharField(label = "名前",widget=forms.TextInput(attrs={'placeholder':'スポティパイ太郎'}))
    user_mail = forms.EmailField(label = "メール",widget=forms.TextInput(attrs={'placeholder':'aaa@gmail.com'}))
    user_pass = forms.CharField(label = "パスワード",widget=forms.PasswordInput(attrs={'placeholder':'6字以上'}))
    user_image = forms.ImageField(label = "画像",)
    user_birthday = forms.DateTimeField(label = "誕生日",widget=forms.TextInput(attrs={'placeholder':'20002020'}))        

class CommentForm( forms.ModelForm ):
    class Meta:
        model = Comment
        fields = ('comment_text',)
        labels = { 'comment_text': '' }

class UploadImageForm( forms.ModelForm ):
    class Meta:
        required=False,
        model = UploadImage
        fields = ['image']

class UsernameForm(forms.Form):
    """履歴削除"""
    NewUsername = forms.CharField(
        required=False,
        min_length=1,
        max_length=16,
        widget=forms.TextInput(
            attrs={
                'placeholder': ''
            }
        )
    )

class RegisterForm( forms.ModelForm ):
    class Meta:
    #username = forms.CharField(label = "ユーザー名",widget=forms.TextInput(attrs={'placeholder':'アーツ三郎'}))
    #email = forms.EmailField( label="メールアドレス", widget=forms.TextInput(attrs={'placeholder':'arts@gmail.com'}) )
        model = CustomUser
        fields = [ 'username', 'email', 'password' ]
        labels = {'username': 'ユーザー名', 'email': 'メールアドレス', 'password': 'パスワード'}

class MusicRegisterForm( forms.ModelForm ):
    class Meta:
        required=False,
        model = Music
        fields = [ 'music_name', 'music_track_full', 'music_track_preview', 'music_album_id']
        labels = {'music_name': '曲名'}


class AlbumRegisterForm( forms.ModelForm ):
    class Meta:
        required=False,
        model = Album
        fields = [ 'album_name', 'album_image', 'album_userid']
        labels = {'album_name': 'アルバム名'}

cwm/cwmapp/templates/cwm/album.html
{% extends "cwm/base.html" %}
{% load static %}
{% block title %}album{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/artist.css' %}">
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/album.css' %}">
<main>
    <!--ローディング画面ここから-->
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
    <div id="loading">
        <div class="logo">
            <img alt="CWM" src="{% static 'img/tmp/logo.png'%}">
            <span>Connect With Music</span>
        </div>
        <div class="fingerprint-spinner">
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
            <div class="spinner-ring"></div>
        </div>
    </div>
    <!--ここまで-->
    {% if is_original %}
        <div id="box1">
            <div class="artist">
                {% if artist_album.image.0.url %}
                    <img src="/media_local/{{ artist_album.image.0.url }}" alt="">
                {% else %}
                    <img src="{% static 'img/users/baseuser.jpg' %}" alt="">
                {% endif %}
                <p class="bigtext">{{ artist_album.name }}</p>
                <p class="bigtext"><a href="{% url 'user' artist_album.artists.id %}">{{ artist_album.artists.name }}</a></p>
            </div>
        </div>
        <div id="box2">
            <div class="artist-flex">
                <p class="bigtext">タイトル</p>
                <div class="album">
                    {% for i in album_items %}
                        <div class="albumbox">
                            <button class="PlaySongBT" type="button" value="/media_local/{{ i.preview_url }}" onclick="PlayMusic('/media_local/{{ i.preview_url }}', this)">
                                <img src="{% static 'img/tmp/play_green.png' %}" alt="">
                            </button>
                            <div class="AlbumNameBox">
                                <p class="AlbumNameText"><a href="{% url 'mus' i.id %}">{{ i.name }}</a></p>
                                <hr>
                                <p class="AlbumNameText"><a href="{% url 'user' i.artists.id %}">{{ i.artists.name }}</a></p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <div id="box1">
            <div class="artist">
                {% if artist_album.images.1 %}
                    <img src="{{ artist_album.images.1.url }}" alt="">
                {% else %}
                    <img src="{% static 'img/users/baseuser.jpg'%}" alt="">
                {% endif %}
                <p class="bigtext">{{ artist_album.name }}</p>
                <p class="bigtext"><a href="{% url 'artist' artist_album.artists.0.id%}">{{artist_album.artists.0.name}}</a></p>
            </div>
        </div>
        <div id="box2">
            <div class="artist-flex">
                <p class="bigtext">タイトル</p>
                <div class="album">
                    {% for i in album_items %}
                    <div class="albumbox">
                        <button class="PlaySongBT" type="button" value="{{ i.preview_url }}" onclick="PlayMusic('{{ i.preview_url }}',this);">
                            <img src="{% static 'img/tmp/play_green.png' %}">
                        </button>
                        <div class="AlbumNameBox">
                            <p class="AlbumNameText"><a href="{% url 'mus' i.id %}">{{ i.name }}</a></p>
                            <hr>
                            <p class="AlbumNameTextMini"><a href="{% url 'artist' i.artists.0.id %}">{{ i.artists.0.name }}</a></p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
</main>
<script type="text/javascript">
    var PlayBTimg = "<img src='{% static 'img/tmp/play_green.png' %}'>";
    var StopBTimg = "<img src='{% static 'img/tmp/stop.png' %}'>";
</script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/album.js' %}"></script>
{% endblock %}

cwm/cwmapp/templates/cwm/changepassword.html
{% extends "cwm/base.html" %}
{% load static %}
{% block title %}パスワード変更{% endblock %}
{% block content %}
<main>
    <link rel="stylesheet" href="{% static 'css/Login.css' %}">
    <link rel="stylesheet" href="{% static 'css/password.css' %}">
    <div class="box1">
        <form id="RegForm" action="{% url 'changepassword' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="titletext">パスワードの変更</h1>
            <hr>
            <div class="FormBox">
                <p class="formtext">現在のパスワード</p>
                <input type="password" class="InputText" placeholder="現在のパスワード" name="oldpassword" id="oldpassword" required>
                <span class="PassAlert old"></span>
            </div>
            <div class="FormBox">
                <p class="formtext">現在のパスワード(確認)</p>
                <input type="password" class="InputText" placeholder="現在のパスワード(確認)" name="oldpasswordcheck" id="oldpasswordcheck" required>
                <span class="PassAlert oldcheck"></span>
            </div>
            <hr>
            <div class="FormBox">
                <p class="formtext">新しいパスワード</p>
                <input type="password" class="InputText" placeholder="新しいパスワード" name="newpassword" id="newpassword" required>
                <span class="PassAlert new"></span>
            </div>
            <div class="FormBox">
                <p class="formtext">新しいパスワード(確認)</p>
                <input type="password" class="InputText" placeholder="新しいパスワード(確認)" name="newpasswordcheck" id="newpasswordcheck" required>
                <span class="PassAlert newcheck"></span>
            </div>
            <div class="FormBox">
                <div class="SubBTBox">
                    <input type="submit" class="loginBT" id="submit" value="パスワードを変更する">
                </div>
            </div>
            <hr>
            <div class="linkbox">
                <p class="descText">パスワードを忘れてしまった場合は<a class="greentext" href="{% url 'register' %}">メールを送信</a></p>
            </div>
        </form>
    </div>
    <script src="{% static 'js/setting.js' %}"></script>
    <script src="{% static 'js/setpass.js' %}"></script>
</main>
{% endblock %}

cwm/cwmapp/templates/cwm/login.html
{% extends "cwm/base.html" %}
{% load static %}
{% block title %}login{% endblock %}
{% block content %}
<main>
    <link rel="stylesheet" href="{% static 'css/Login.css' %}">
    <div class="box1">
        <form id="RegForm" action="{% url 'Login' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="titletext">CWMにログイン</h1>
            <hr>
            <div class="FormBox">
                <p class="formtext">メールアドレス</p>
                <!-- {{viewsで置き換えておく}}-->
                <input type="email" class="InputText" placeholder="メールアドレス" name="email">
            </div>
            <div class="FormBox">
                <p class="formtext">パスワード</p>
                <!-- {{viewsで置き換えておく}}-->
                <input type="password" class="InputText" placeholder="パスワード" name="password">
            </div>
            <div class="FormBox">
                <div class="SubBTBox">
                    <!-- {{viewsで置き換えておく}}-->
                    <input type="submit" class="loginBT" id="submit" value="ログイン">
                </div>
            </div>
            <hr>
            <div class="linkbox">
                <p class="descText">アカウントをお持ちでない方は<a class="greentext" href="{% url 'register' %}">新規登録</a></p>
                <p class="descText">パスワードを忘れてしまった場合は<a class="greentext" href="{% url 'changepassword'%}">パスワード変更</a></p>
            </div>
        </form>
    </div>
    <script src="{% static 'js/setting.js' %}"></script>
</main>
{% endblock %}

cwm/cwmapp/templates/cwm/register.html
{% extends "cwm/base.html" %}
{% load static %}
{% block title %}新規登録{% endblock %}
{% block content %}
<main>
    <link rel="stylesheet" href="{% static 'css/Login.css' %}">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <div class="box1">
        <form id="RegForm" action="{% url 'register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="titletext">CWMに新規登録</h1>
            <hr>
            <div class="FormBox">
                <p class="formtext">ユーザー名</p>
                <input type="text" class="InputText" placeholder="ユーザー名" name="username" required id="id_username">
            </div>
            <div class="FormBox">
                <p class="formtext">メールアドレス</p>
                <input type="email" class="InputText" placeholder="メールアドレス" name="email" required id="id_email">
            </div>
            <div class="FormBox">
                <p class="formtext">パスワード</p>
                <input type="password" class="InputText" placeholder="パスワード" name="password" required id="id_password">
                <span onclick="PassLook()" id="PassLook">
                    <img src="{% static 'img/tmp/eye_open.png' %}" alt="eye">
                </span>
                <span class="PassAlert new"></span>
            </div>
            <div class="FormBox">
                <p class="formtext">パスワード(確認)</p>
                <input type="password" class="InputText" placeholder="パスワード(確認)"required id="id_passwordcheck">
                <span class="PassAlert newcheck"></span>
            </div>
            <div class="FormBox">
                <div class="SubBTBox">
                    <input type="submit" class="loginBT" id="submit" value="新規登録">
                </div>
            </div>
            <hr>
            <div class="linkbox">
                <p class="descText">アカウントをすでにお持ちの方は<a class="greentext" href="{% url 'Login' %}">ログイン</a></p>
            </div>
        </form>
    </div>
    <script src="{% static 'js/setting.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
    <script type="text/javascript">
        var eye_opentex = "<img src='{% static 'img/tmp/eye_open.png' %}'>";
        var eye_closetex = "<img src='{% static 'img/tmp/eye_close.png' %}'>";
    </script>
</main>
{% endblock %}

cwm/cwmapp/templates/cwm/upload.html
{% extends "cwm/base.html" %}
{% load static %}
{% block title %}音楽をアップロード{% endblock %}
{% block content %}
<main>
    <link rel="stylesheet" href="{% static 'css/Login.css' %}">
    <link rel="stylesheet" href="{% static 'css/upload.css' %}">
    <div class="box1">
        <form id="RegForm" action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="titletext">音楽をアップロード</h1>
            <hr>
            <div class="FormBox">
                <p class="formtext">曲名</p>
                <input type="text" class="InputText" placeholder="曲名" name="music_name" required id="id_music_name">
            </div>
            <div class="FormBox">
                <p class="formtext">音源ファイル（フル）</p>
                <div class="songbox">
                    <span id="full_prebox">
                        <h3 class="greentext">アップロードしてください</h3>
                    </span>
                    <span class="filebox">
                        <p class="SongFileName" id="full_filename"></p>
                        <span class="inputfile">
                            <input type="file" name="music_track_full" accept="audio/*" required id="id_music_track_full">
                        </span>
                    </span>
                </div>
            </div>
            <div class="FormBox">
                <p class="formtext">音源ファイル（プレビュー）</p>
                <div class="songbox">
                    <span id="pre_prebox">
                        <h3 class="greentext">アップロードしてください</h3>
                    </span>
                    <span class="filebox">
                        <p class="SongFileName" id="pre_filename"></p>
                        <span class="inputfile">
                            <input type="file" name="music_track_preview" accept="audio/*" required id="id_music_track_preview">
                        </span>
                    </span>
                </div>
            </div>
            <div class="FormBox">
                <p class="formtext">アルバム</p>
                <div class="songbox">
                    <div id="albumbox">
                        <label for="Albums_1" class="album_radio">
                            <img class="UserAlbumIcon" src="{% static 'img/tmp/plus.png' %}" alt="アルバム画像">
                            <p class="whitetext">シングルとして追加</p>
                            <input type="radio" id="Albums_1" name="SelectAlbum" value="Single" checked>
                        </label>
                        <label for="Albums_3" class="album_radio">
                            <img class="UserAlbumIcon" src="{% static 'img/tmp/add_album.png' %}" alt="アルバム画像">
                            <p class="whitetext">アルバムを追加</p>
                            <input type="radio" id="Albums_3" name="SelectAlbum" value="MakeAlbum">
                        </label>
                        <p class="whitetext">作成したアルバム</p>
                        <!-- ↓ユーザーがアルバムを作っていたら表示↓ -->
                        {% if Albums %}
                        {% for i in Albums %}
                        <label for="{{i.album_id}}" class="album_radio">
                            <img class="UserAlbumIcon" src="{{i.album_image.url}}" alt="アルバム画像">
                            <p class="whitetext">{{i.album_name}}</p>
                            <input type="radio" id="{{i.album_id}}" name="SelectAlbum" value="{{i.album_id}}">
                        </label>
                        {% endfor %}
                        {% endif %}
                        <!-- ↑ユーザーがアルバムを作っていたら表示↑ -->
                    </div>
                    <div id="albumdesc">
                        <div id="IconBox">
                            <h3 class="whitetext">アルバム画像</h3>
                            <div class="AlbumForm">
                                <img id="AlbumIcon" class="AlbumIcon" src="{% static 'img/tmp/仮アルバム.jpg' %}" alt="アルバム画像">
                                <div>
                                    <span id="FilenameText" class="whitetext">画像を設定してください</span>
                                    <span class="inputfile">
                                        <input type="file" name="album_image" accept="image/*" id="id_album_image">
                                    </span>
                                </div>
                            </div>
                            <input type="text" class="AlbumInputText" placeholder="アルバム名" name="album_name" id="id_album_name">
                        </div>
                    </div>
                </div>
            </div>
            <div class="FormBox">
                <div class="SubBTBox">
                    <input type="submit" class="loginBT" id="submit" value="音楽のアップロード">
                </div>
            </div>
        </form>
    </div>
    <script src="{% static 'js/setting.js' %}"></script>
    <script src="{% static 'js/upload.js' %}"></script>
</main>
{% endblock %}